---
kind: pipeline
type: kubernetes
name: cms-login-develop
steps:
  - name: build-cms-login
    image: node:12.9.1-alpine
    commands:
      - npm install
      - npm run build

  - name: publish-gcr-cms-login
    image: plugins/gcr
    settings:
      repo: ding4pro/4ding/cms-login
      cache_from: ding4pro/4ding/cms-login
      registry: asia.gcr.io
      json_key:
        from_secret: gcr_credential
      tags:
        - "latest"
      dockerfile: drone-ci/Dockerfile

trigger:
  branch:
    - develop
  event:
    - push

---
kind: pipeline
type: kubernetes
name: cms-login-main
steps:
  - name: build-cms-login
    image: node:12.9.1-alpine
    commands:
      - npm install
      - npm run build

  - name: publish-gcr-cms-login
    image: plugins/gcr
    settings:
      repo: ding4pro/4ding/cms-login
      cache_from: ding4pro/4ding/cms-login
      registry: asia.gcr.io
      json_key:
        from_secret: gcr_credential
      tags:
        - ${DRONE_TAG}
      dockerfile: drone-ci/Dockerfile

trigger:
  event:
    - tag
