kind: pipeline
type: docker
name: 4d-cms-login
steps:
  - name: build-cms-login
    image: node:12.9.1-alpine
    commands:
      - npm install
      - npm run build

  # - name: publish-cms-login
  #   image: plugins/docker
  #   settings:
  #     username:
  #       from_secret: docker_hub_username
  #     password:
  #       from_secret: docker_hub_password
  #     repo: 4ding/cms-login
  #     cache_from: 4ding/cms-login
  #     tags:
  #       - "latest"
  #       - "0.0.0"
  #     dockerfile: drone-ci/Dockerfile
      
  - name: publish-gcr-cms-login
    image: plugins/gcr
    settings:
      repo: ding4pro/4ding/cms-login
      cache_from: ding4pro/4ding/cms-login
      registry: asia.gcr.io
      json_key:
        from_secret: gcr_credential
      tags:
        - "latest"
      dockerfile: drone-ci/Dockerfile

trigger:
  branch:
  - main
  event:
  - push

